// *************************** YOUR CODE BELOW *******************************
//******************TEST EARLY AND OFTEN USING console.log() ******************
//****************** SERIOUSLY TEST USING console.log()!!! ******************

$(".btn").click(function(){
    console.log('click');
    $('.gallery').empty();
    //assigns the value being seacrched to a veriable
    //ST is the Search Term
    /*global $*/
    var ST = $('#srch-term').val();
    //X is the URL
    var x = "https://api.giphy.com/v1/gifs/search?q=" + ST + "&api_key=dc6zaTOxFJmzC";
    
    $.ajax({
        url: x,
        method: "GET",
        //Runs only if Successful
        success: function(response){
            //Appends the random whole number generated by ver randIndex
            var randIndex = Math.floor(Math.random() * response.data.length);
            $('.gallery').append(
                '<div class="col-md-offset-4 col-md-4 thumb">\
                    <a class="thumbnail" href =' + response.data[randIndex].images.fixed_width.url + '>\
                        <img src=' + response.data[randIndex].images.fixed_width.url + '/>\
                    </a>\
                </div>'
                
                
            );
        },
    }); 
});
